### ISSUE TITLE
Exclusion for Service type Of ADNS

### ISSUE THREAD

**Issue by ghost** [cstalhood/Get-ADCUnusedObjects#1]
Dear Carl,
recently i used your script to find the unused object in Netscaler.
However in my config i have a service that act like ADNS service.
As you know this kind of service usually is not bind to any vip.
It would be great if this type of service is considered valid and then excluded from thinking that it's unused.
Regards
Christian T.

**Comment by cstalhood** [comment]
It should already be excluding ADNS services. Can you provide some sample CLI commands that it doesn't exclude properly?

**Comment by ghost** [comment]
Sure..

#NS12.1 Build 50.31
#Last modified by save config, Wed Apr 17 14:09:19 2019
set ns config -IPAddress 192.168.10.10 -netmask 255.255.0.0
enable ns feature WL SP LB CS CR SSL GSLB AAA REWRITE RESPONDER AppFlow CH
enable ns mode FR USNIP PMTUD
add service svc_adns_internal_workers_com gslbpd_workers_com ADNS 53 -gslb NONE -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport NO -sp OFF -cltTimeout 120 -svrTimeout 120 -CKA NO -TCPB NO -CMP NO
add appfw JSONContentType "^application/json$" -isRegex REGEX
add appfw XMLContentType ".*/xml" -isRegex REGEX
add appfw XMLContentType ".*/.*\\+xml" -isRegex REGEX
add appfw XMLContentType ".*/xml-.*" -isRegex REGEX
set ip6TunnelParam -srcIP ::
set ptp -state ENABLE
set ns param -cookieversion 1 -timezone "GMT+01:00-CET-Europe/Rome"
set ns cqaparam -lr1probthresh 0.00e+00 -lr2probthresh 0.00e+00
set qos parameters -debuglevel 0 -dumpcore 4294967295 -dumpsession 0 -dumpqp 0
set urlfiltering parameter -HoursBetweenDBUpdates 24 -TimeOfDayToUpdateDB 03:00 -MaxNumberOfCloudThreads 4 -CloudKeepAliveTimeout 120000 -CloudServerConnectTimeout 1000 -CloudDBLookupTimeout 2000 -seedDBSizeLevel 1 -LocalDatabaseThreads 1
set videooptimization parameter -RandomSamplingPercentage 0.00e+00

and the result of UnusedObjects.txt is

#Unused ADC objects
#Services
#--------
rm service svc_adns_internal_workers_com

**Comment by cstalhood** [comment]
I think I fixed it. I was looking for IP Address instead of Server Object.

**Comment by ghost** [comment]
Great, i'll try the fixed version later.
ThankYou
