### ISSUE TITLE
Running on MacOs Mojave

### ISSUE THREAD

**Issue by ghost** [cstalhood/Get-ADCUnusedObjects#2]
Hi Carl,

i don't know if this is a issue, perhaps to run the script on MacOs Mojave i change the 
following lines lines:

Line 15
From
`[string]$outputFile = "$env:userprofile\Downloads\UnusedObjects.txt",`
to
`[string]$outputFile = "$env:HOME/Downloads/UnusedObjects.txt",`

Line 19
From
` [string]$textEditor = "c:\Program Files (x86)\Notepad++\notepad++.exe"`
to
`[string]$textEditor = "/usr/local/bin/code"`

In this case i use Visual Studio Code.

Regards

**Comment by cstalhood** [comment]
I added some conditionals for Mac. Let me know if that fixes it.

**Comment by ghost** [comment]
Hi Carl,

great , now is working correctly on MacOS
Thanks.
