### ISSUE TITLE
Transform Action

### ISSUE THREAD

**Issue by ghost** [cstalhood/Get-ADCUnusedObjects#3]
Hi Carl,
could you check the following behavior that i encounter :

from the attached netscaler config i get the following results

# Unused ADC objects
# Transform Actions
# -----------------
rm transform action url_trasf_act_helpcenter_jira_8080
rm transform action url_trasf_act_helpcenter_jira_8080_v2

but i think isn't correct 

[temp_conf_carlstalhood.txt](https://github.com/cstalhood/Get-ADCUnusedObjects/files/3302299/temp_conf_carlstalhood.txt)

Let me know if i made a mistake.
Regards

**Comment by cstalhood** [comment]
Thanks for reporting this. I'll look into it when I can.

**Comment by cstalhood** [comment]
I think it's fixed now.

Since Transform Actions are removed when the Transform Profile is removed, there's no need to report on them.
